name:                Euler-Problem-001Haskell
version:             0.1.0.0
github:              "charltonaustin/Euler-Problem-001Haskell"
license:             BSD3
author:              "Charlton Austin"
maintainer:          "charlton.austin@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/charltonaustin/Euler-Problem-001Haskell#readme>

dependencies:
- base >= 4.11 && < 10
- hspec
- QuickCheck
- rio >= 0.1.12.0

library:
  source-dirs: src

executables:
  Euler-Problem-001Haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Euler-Problem-001Haskell

tests:
  Euler-Problem-001Haskell-test:
    main:                GenerateThreeAndFiveSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Euler-Problem-001Haskell
